// <auto-generated />
namespace TallerIV.Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cartaDePresentacionPostulante : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cartaDePresentacionPostulante));
        
        string IMigrationMetadata.Id
        {
            get { return "201710010708086_cartaDePresentacionPostulante"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
